### ISSUE TITLE
Documentation for Reprogramming is vague in some places

### ISSUE THREAD

**Issue by dirkruiken** [tobychui/MCH-PD-Automatic-Reflow-Hotplate#1]
Hi -

I was trying to reprogram the board and had trouble with the documentation. Can you add which board type you select in the Arduino IDE (and what source you are using if that is a custom board definition)?
Also for the USB flashing description, is the board already powered up with the usb-c connector when I add the jumper & insert the programmer usb cable? If it was not powered up yet, adding the jumper and plugging usb programmer in at the same time would be the same as first applying the jumper to the unpowered board and then plugging it in, no?

Thanks, Dirk

**Comment by tobychui** [comment]
Hi @dirkruiken , thanks for the wait. It is Lunar New Year holiday here in Taiwan and I didn't check Github for a few days. 

Have you read the hackaday post regarding the usage and assembly of the MCH hotplate before purchase? If no, here is the [link](https://hackaday.io/project/194305-diy-usb-pd-powered-mch-automatic-reflow-hotplate).

In simple words, you will need to install the ch55x arduino library and select CH552 as the target board for uploading your code. The board library can be downloaded [here](https://github.com/DeqingSun/ch55xduino).

The usb-C connector is not for programming. It is for PD power only. To program it, use the 4 pin 2.54 header labeled USB (5V, D-, D+ and GND) by connecting a USB male header to it and insert it into your computer. The firmware should have an emulated USB serial device which you can directly program via Arduino IDE by selecting the targeted COM port (or tty if you are using Linux) in Serial upload mode. So if you see a COM port pop up after you inserted the hotplate to your computer, you do not need to bridge the jumper for entering the USB upload mode.

If you have difficulties flashing the chip, you can refer to the ch55xduino repo for detailed information. The MCH hotplate MCU portion of the circuit is basically based on Deqing Sun's design so all instruction on his repo are applicable to this device as well.

Feel free to tag me and add a comment if you need further help :)

**Comment by tobychui** [comment]
Closing issue as no follow up questions were asked.
